### ISSUE TITLE
Support async created apps

### ISSUE THREAD

**Issue by seriouslag** [VladimirMikulic/route-list#1]
This library should support async apps (awaiting the default import of the app)

My apps usually have an async startup and this library cannot be used on my app.
This library would be useful if it resolved any promises returned by the app.

**Comment by VladimirMikulic** [comment]
Thanks for reporting this @seriouslag.
Could you give me an example of this async app approach?

**Comment by jdesboeufs** [comment]
For example:

```js
async function main() {
  await mongo.connect()
  const app = express()
  ...
  app.listen(5000)
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
```

**Comment by VladimirMikulic** [comment]
Thanks @jdesboeufs.
Support published in latest version. (check README)
