### ISSUE TITLE
Plans to make it also as a middleware

### ISSUE THREAD

**Issue by ruxxzebre** [VladimirMikulic/route-list#10]
Do you have any plans to make it also as a middleware or library for express or koa?
As one time usage, by passing application object, in case of express, into a function from this project.
Would be great, kind of hapi-print-routes!

Good work!

**Comment by VladimirMikulic** [comment]
Hi @ruxxzebre. Thanks for the input.
I'm wondering in which cases do you think it would be useful?

**Comment by ruxxzebre** [comment]
@VladimirMikulic observing list of routes you've implemented when server starts can be quite useful sometimes, not for production, but for something like debugging purposes.
UPD: there's plugin for hapi, probably _hapi-print-routes_, can't tell for sure, but certainly had it when worked on hapi project.

**Comment by VladimirMikulic** [comment]
Sounds good. In that case, I'll expose the programmatic API so you can import the package and use it as you see fit.

**Comment by VladimirMikulic** [comment]
I appreciate your patience on this @ruxxzebre.
The functionality is now available as a part of route-list@1.3.0
