### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by Eliasyoussef47** [VladimirMikulic/route-list#11]
![image](https://user-images.githubusercontent.com/31613492/227241010-00f0ff25-233e-4dd4-9d0b-2de09fdced97.png)
![image](https://user-images.githubusercontent.com/31613492/227241090-f148da5a-53f3-44e8-884d-465cd1121e3f.png)
![image](https://user-images.githubusercontent.com/31613492/227241439-38da4767-172d-41a1-9732-9bd36cf8cb22.png)
### Folder in node_modules:
![image](https://user-images.githubusercontent.com/31613492/227241570-3a4083b6-cd31-479f-9650-0f19a2134f9e.png)

**Comment by VladimirMikulic** [comment]
@Eliasyoussef47 thank you for reporting this issue.
Please install 1.3.2 and everything should work now!

**Comment by Eliasyoussef47** [comment]
@VladimirMikulic Thank you
