### ISSUE TITLE
It should recognize other folder structures

### ISSUE THREAD

**Issue by axelsomerseth** [VladimirMikulic/route-list#4]
Hi there!

When I tried this package, I gave the following input:
```bash
route-list --group --methods source/app.ts

# I also tried:
route-list --group --methods ./source/app.ts
```

I got the following error/output message:

```
error: missing required argument 'appjs-file'

Usage: route-list [options] <appjs-file>

Beautifully shows Express/Koa/Hapi/Fastify routes in CLI.

Options:
  -g, --group                  Display routes in groups separated with new line
  -m, --methods <methods>      Include routes registered for HTTP method(s)
  -i, --include-paths <paths>  Include routes starting with path(s)
  -e, --exclude-paths <paths>  Exclude routes starting with path(s)
  -V, --version                output the version number
  -h, --help                   display help for command

Examples:
  $ route-list server/app.js
  $ route-list --methods GET,POST server/app.js
  $ route-list --include-paths /users,/events server/app.js
```

This is my folder structure 
(`./source/app.ts` file contains the `const app: Express = express();` initialization): 
```
.
├── build/
│ └── ...
├── coverage/
│ └── ...
├── node_modules/
│ └── ...
├── source/
│ ├── db/
│ ├── handlers/
│ ├── middlewares/
│ ├── public/
│ ├── repository/
│ ├── routes/
│ ├── schemas/
│ ├── services/
│ ├── types/
│ ├── utils/
│ ├── views/
│ ├── app.ts
│ └── index.ts
├── .env.example
├── jest.config.ts
├── package-lock.json
├── package.json
├── README.md
└── tsconfig.json
```

Additional Info:
- Node.js v16.17.0
- Express v4.18.2
- TypeScript v4.8.4

**Comment by VladimirMikulic** [comment]
Hi @axelsomerseth! Thanks for reaching out!
You haven't provided a correct argument to `--methods` option.

The option is used when you only want to see routes that are registered for method.
(e.g. `--methods GET,POST,PUT` will only show routes registered for GET, POST and PUT respectively)

If you want to see all routes (default behavior), you don't need `--methods` option.
In your case, it would be `route-list --group ./source/app.ts`

Let me know if that helps!

**Comment by axelsomerseth** [comment]
Thanks for your reply @VladimirMikulic 

I was using this package in the wrong way.

But, I have the following error without using the methods option.

Given the following input:

```
route-list --group ./source/app.ts

# I also tried:
route-list --group source/app.ts
```

I got the following error:

![Screen Shot 2022-10-28 at 13 55 19](https://user-images.githubusercontent.com/18746251/198721559-95d070d8-3f14-4bbc-8625-7b91fcca3897.png)

(Notice in the screenshot that the `cat` command works well)

**Comment by VladimirMikulic** [comment]
Thanks for detailed screenshot @axelsomerseth.
I refactored TS functionality to be more robust and now it should all work.

**Comment by axelsomerseth** [comment]
You're welcome @VladimirMikulic 

Best Regards!
