### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by dailypixie** [VladimirMikulic/route-list#5]
>npx route-list ./src/api/app.js                                   
Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received 
protocol 'd:'

**Comment by VladimirMikulic** [comment]
Hi @dailypixie! Thanks for the report.
This should now be resolved in the latest version.

**Comment by dailypixie** [comment]
Thank you!
